version: '1.0.0.{build}'
image:
- Visual Studio 2019
environment:
  nodejs_version: "10.4.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - cmd: npm dist